### ISSUE TITLE
Support for Symfony LTS versions

### ISSUE THREAD

**Issue by acardielwata** [auth0/symfony#144]
Hi,

Thanks for the release! It's a great new! I have been tracking this repo for months looking for a new release compatible with Symfony 5.4. Today was released the new version 5.0.0 but only compatible from Symfony 6.1+. Previous version 4.0.0 was not compatible with Symfony 5.4 (many deprecation warnings) because the old authenticator format. 

Taking a look to #130 one of main goal it's support for 5.1+ versions (and also for 6+) but in composer.json (and Readme) the minimal required version it's 6.1. 

It's possible to consider adapt code for this Long Term Support version of Symfony? 

Thanks for your effort and your work.

**Comment by evansims** [comment]
Hi @acardielwata, thanks for your question and kind words!

I do agree it isn't ideal not having support for the LTS build at the moment, but it's a bit of a perfect storm of necessity that has stopped us from offering that at the moment. Too many of the underlying dependencies in the 4.x branch are deprecated and unsupported for us to continue offering official support on that, I'm afraid.

That said, developers are of course free to continue using the 4.x branch as long as they need, and we'll keep helping as much as we can to ensure their experience is a positive one.

We do hope to offer full and proper LTS support going forward, but we won't be able to do that until an LTS release is made on the Symfony 6 line. Sorry about that!
