### ISSUE TITLE
Looks like your recipe isn't working. As a result the bundles file isn't being updated. 

### ISSUE THREAD

**Issue by rvdavidx** [auth0/symfony#146]
### Describe the problem
Looks like your recipe isn't working. As a result the bundles file isn't being updated. 

### What was the expected behavior?
At a minimum, the configuration noted on here should be done automatically via recipes. 
I managed to get around it by following your instructions, however, the one key piece that was missing was the addition of the bundle file to the bundles.php in symfony. 

As a workaround, if users are seeing messages like: There is no extension able to load the configuration for "auth0" [...]
It's just adding the following line to your bundles.php

`
Auth0\Symfony\Auth0Bundle::class => ['all' => true]
`

Here's a full example of what the bundles.php should look like: 
```

<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Auth0\Symfony\Auth0Bundle::class => ['all' => true],
];

```

### Reproduction
- create a fresh symfony project.
- issue a composer require auth0/symfony
- recipe should run which does all the configuration. 

### Environment

- PHP 8.2
- Symfony 6.2.4

**Comment by evansims** [comment]
Hi @rvdavidx 👋 Thanks for your report! Hmm, that's strange! Let me check into that. I don't believe that should have been required. Is your Symfony project using Flex?

**Comment by AriesXIX** [comment]
So did you add it? I ran into this same issue forgetting that I've solved it already - I've wasted an hour trying to debug it.
