### ISSUE TITLE
Is the package compliant with a SPA using Symfony as API ?

### ISSUE THREAD

**Issue by vince83110** [auth0/symfony#150]
### Describe the problem you'd like to have solved

According to this other github repo: https://github.com/auth0-developer-hub/api_symfony_php_hello-world, they use the auth0 php sdk to handle a project using React as frontend and Symfony as an API, everything is described on this code sample: https://developer.auth0.com/resources/code-samples/full-stack/hello-world/basic-access-control/spa/react-javascript/symfony-php (nice work by the way !).
But it makes to handle a lot of things which can be indeed packaged (provider, model and so on).

### Describe the ideal solution

I just started to read docs and found this SDK for Symfony, I use Symfony 6.2 (with api/platform & stateless session) and React, does this package compliant with this way of doing ? or this package is used only for a _regular web application_ ?

Thanks, my knowledge of auth0 is pretty poor for now, I just want to be sure I can use this package instead of defining many things on my own.

**Comment by evansims** [comment]
Hi @vince83110 👋 Thanks for your question! Yes, this SDK supports both stateful and stateless application types.

While I'm not familiar with that repository offhand, in a stateless configuration, the SDK consumes access tokens supplied as headers with incoming requests. So, generally speaking, the SDK is completely agnostic as to the origin of the token. Whatever shape your frontend application might take, all you need is to pass those tokens with requests to your Symfony application. 👍
