### ISSUE TITLE
Problem with redirectUri

### ISSUE THREAD

**Issue by apsylone** [auth0/symfony#159]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, 

I have subdomains in my application :
- app.domain.wip
- www.domain.wip
- admin.domain.wip

I'm using the "host" argument for generating my routes.

Actually, I met a problem with the redirectUri generated by auth0/symfony.

I've followed all the steps (no more) in the Readme and my redirectUri is looking at : 
"https://app.planners.wip//www.planners.wip"

I'm wondering if it could be a bug because of my configuration about "host" ? It seems to not generate the absolute url with the scheme.

Any help would be greatly appreciated :)

Cheers,

### Reproduction

1. Follow the Readme for configuration
2. Create controller with subdomain (host)
3. Try to connect
4. Error on auth0 when logout

invalid_request: The "returnTo" querystring parameter "**https://app.domain.wip//www.domain.wip/**" is not defined as a valid URL in "Allowed Logout URLs". To add a new URL, please do it here: https://manage.auth0.com/#/applications/xxxxxxxxx/settings

TRACKING ID: 919365f98da6e3e840db

### jwt-auth-bundle version

latest

### Symfony version

latest

### PHP version

8.1

**Comment by evansims** [comment]
Thanks @apsylone 👋 I'll investigate this and get back to you

**Comment by evansims** [comment]
I'm having trouble fully understanding the issue you've described. Have you assigned the `redirect_uri` value in the SDK's configuration? If unassigned, the SDK will make a best guess effort at determining the intended destination.

It might help to provide a sample of the relevant code for your scenario.

**Comment by apsylone** [comment]
If we look at the returnTo parameter, we found this : "https://app.domain.wip//www.domain.wip/"".
We could this there is a problem in it (double domains, one without the scheme)...
Sadly, I don't have relevant code as we abandoned Auth0 because we weren't able to make it work with our projet...
