### ISSUE TITLE
Authenticator does not allow PUBLIC_ACCESS role

### ISSUE THREAD

**Issue by JanMikes** [auth0/symfony#160]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, i am using stateful auth. The usecase is like this - i have page, that should be accessible by both unauthenticated (anonymous) and authenticated users.

I am unable to achieve this, because every time unauthenticated user access the page, it gets redirected to login.

I have step debugged, and i believe that somehow `\Auth0\Symfony\Security\Authenticator` is missing check for`PUBLIC_ACCESS` role - if it is allowed for the request and session is missing, it should allow user to access the page.

### Reproduction

```php
return static function (SecurityConfig $securityConfig): void {
    $securityConfig
        ->provider('auth0_provider')
        ->id(\Auth0\Symfony\Security\UserProvider::class);

    $securityConfig->firewall('main')
        ->provider('auth0_provider')
        ->customAuthenticators(['auth0.authenticator']);

    $securityConfig->accessControl()
        ->path('^/some-public-page$')
        ->roles('PUBLIC_ACCESS');
};
```

With such config, create controller with route to url `/some-public-page`, access it as anonymous user (anonymous tab in browser etc) and instead of accessing the site, you will get redirected to login.

### Additional context

If i tweaked `\Auth0\Symfony\Security\Authenticator::supports()` method, to return false, when `PUBLIC_ACCESS` role is required for the request, it worked as expected -> `$this->getUser()` in controller returns user for authenticated users and null for anonymous.

Other option that worked for me was tweaking `\Auth0\Symfony\Security\Authenticator::onAuthenticationFailure()` - check for `PUBLIC_ACCESS` access control, if there it is, return null, then it worked as intended. 

The key for my workaround was to replace `\Auth0\Symfony\Security\Authenticator` in DIC with my own implementation - it got injected `\Symfony\Component\Security\Http\AccessMapInterface` and then line this:
```php
[$attributes] = $this->map->getPatterns($request);
if ($attributes && [AuthenticatedVoter::PUBLIC_ACCESS] !== $attributes) {
    return null;
}
```

### jwt-auth-bundle version

not-relevant

### Symfony version

6.3.7

### PHP version

8.2.12

**Comment by evansims** [comment]
Hi @JanMikes, thanks for reporting this.

The Authenticator guard is not designed to support anonymous access on routes it's applied to. While this change would be beneficial in cases like this, changing it within the SDK would be a breaking change. We'll need to wait to make such a change until the next major. I have backlogged your suggestion in the meantime for the next major-work opportunity.

**Comment by JanMikes** [comment]
Thank you. 

I appreciate confirming that it is not error on my side :-).

**Comment by JanMikes** [comment]
In case anyone interested, here is how i solved the situation: https://github.com/JanMikes/auth0-symfony/commit/0c98d088750c938d2c40d9f4bca99d5f24ad7f11

I am using this fork in my app.

My security.php config:
```php
return static function (SecurityConfig $securityConfig): void {
    $securityConfig
        ->provider('auth0_provider')
        ->id(UserProvider::class);

    $securityConfig->firewall('dev')
        ->pattern('^/(_(profiler|wdt)|css|images|js)/')
        ->security(false);

    $securityConfig->firewall('main')
        ->pattern('^/')
        ->provider('auth0_provider')
        ->customAuthenticators(['auth0.authenticator']);

    $securityConfig->accessControl()
        ->path('^/(url1|url2)')
        ->roles([AuthenticatedVoter::IS_AUTHENTICATED_FULLY]);

    $securityConfig->accessControl()
        ->path('^/')
        ->roles([AuthenticatedVoter::PUBLIC_ACCESS]);
};
```
