### ISSUE TITLE
Incompatible with Symfony 7

### ISSUE THREAD

**Issue by alebedev80** [auth0/symfony#162]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Please fix composer.json:

    "symfony/cache": "^6.1",
    "symfony/framework-bundle": "^6.1",
    "symfony/security-bundle": "^6.1"
    
 

### Reproduction

Upgrade Symfony from version 6 to 7

### jwt-auth-bundle version

-

### Symfony version

7

### PHP version

8.2

**Comment by evansims** [comment]
Hi @alebedev80, we do not currently support Symfony 7. We expect to support this in a future release but I can't provide an ETA at this time.
