### ISSUE TITLE
Cannot verify signature when php-http/mock-client is required

### ISSUE THREAD

**Issue by alainsharemat** [auth0/symfony#164]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello,

We are unable to authorize a valid token from our app. We get an error `Cannot verify signature: JWKS did not contain the key specified by the token (500 Internal Server Error)`.

The problem is that we have required (require-dev) `php-http/mock-client` for our unit-tests. When the verifier calls the `/.well-known/jwks.json` route, the mock-client replies with an empty response with status 200. The `kid` is not present in the response and we got this error.

We need this require-dev php-http/mock-client for our test but, when we are on our dev environment, using our app, we are making real http requests (with `php-http/curl-client`).

### Reproduction

1. create a symfony project with this bundle
2. composer require php-http/mock-client
4. make call to a route with a bearer

### Additional context

It seems the problem is with https://github.com/psr-discovery/http-client-implementations. The mocking priority clause is quite painful for us. :)

We also tried to specify a value for `auth0.sdk.http_client` (in our auth0.yaml file) but whatever we tried led us to `Auth0\SDK\Configuration\SdkConfiguration::__construct(): Argument #20 ($httpClient) must be of type ?Psr\Http\Client\ClientInterface, string given (500 Internal Server Error)`

What would be the way to make this bundle work when we required the mock-client ?

### jwt-auth-bundle version

5.1.0

### Symfony version

6.3

### PHP version

8.1

**Comment by evansims** [comment]
Hi @alainsharemat 👋

I believe the issue is, at present, the SDK doesn't create a reference for values provided to those HTTP PSR configuration points.

Can you give this branch a try with your code, and see if it resolves the issue? https://github.com/auth0/symfony/tree/feat/add-configurable-http-psrs

**Comment by alainsharemat** [comment]
Hi @evansims :smile: 

I tried it and it worked fine !

Thank you so much :+1:

**Comment by evansims** [comment]
Perfect, glad that did the trick! I have a release in progress that will hopefully go out first of next week, so I'll be sure that is incorporated in there.
