### ISSUE TITLE
Support for Symfony 7.0

### ISSUE THREAD

**Issue by JanMikes** [auth0/symfony#169]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Possibility to install package with Symfony 7.0

### Describe the ideal solution

Just bump dependency in composer.json - at this point im not sure if there are any bc breaks that needs to be solved.

**Comment by evansims** [comment]
We do not currently support Symfony 7, as stated in the README; however, we are working on it.
