### ISSUE TITLE
[5.1.0 -> 5.2.0] Argument $logger no more existing in Auth0\Symfony\Service

### ISSUE THREAD

**Issue by fullmoonissue** [auth0/symfony#173]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi 👋,

Thanks for the lastest release taking care of Sf v6.4.

Dependabot has tried to upgrade the `auth0/symfony` package from `5.1.0` to `5.2.0` but this error is encountered in the CI.

```
In ResolveNamedArgumentsPass.php line 87:

  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  Invalid service "auth0": method "Auth0\Symfony\Service::__construct()" has no argument named "$logger". Check your service definition.
```

Checking the [compare between the two versions](https://github.com/auth0/symfony/compare/5.1.0...5.2.0), we can see that the argument `$logger` has been removed from the class `Service` ([cf](https://github.com/auth0/symfony/blob/5.2.0/src/Service.php#L22)) but it has been kept in the service definition ([cf](https://github.com/auth0/symfony/blob/5.2.0/src/Auth0Bundle.php#L140)).

Locally, when removing the `$logger` argument inside the `Auth0Bundle` from the `Service` class (and rebuild the symfony cache), the same error appears for the `Auth0\Symfony\Security\Authenticator`, `Auth0\Symfony\Stores\SessionStore` and `Auth0\Symfony\Security\Authorizer` too.

After removing all the `$logger` arguments from the definitions, a new error appears : `Invalid service "Auth0\Symfony\Security\UserProvider": class has no constructor.`, so I've added a `__construct()` method like this : 

```
    public function __construct(
        private Service $service,
    )
    {
    }
```

After those updates, the cache clears.

Do I mistaken about the spotted errors ?

If desired, I can make a PR with the mentioned updates.

Kind regards,

### Reproduction

Trying to upgrade from the version `5.1.0` to `5.2.0`.

### jwt-auth-bundle version

5.2.0

### Symfony version

6.4.1

### PHP version

8.2.11

**Comment by evansims** [comment]
Hi @fullmoonissue 👋 Thanks for reporting this! Looks like the constructor got caught up in an overzealous Rector rule, with the new code styling getting applied. I'll get a fix cut right away.

**Comment by evansims** [comment]
👋 Could you give https://github.com/auth0/symfony/tree/fix/rector-signature-changes a look/try and check if that resolves all the method signature alterations you identified?

**Comment by fullmoonissue** [comment]
Hi @evansims,

Thanks for the quick reply.

Indeed, when branching on `dev-fix/rector-signature-changes` from composer there's no more issue afterwards, nice.

It's a ✅ on my side.

**Comment by evansims** [comment]
Excellent, thanks so much for confirming that for me! I'll get a patch release going with that fix right now
