### ISSUE TITLE
[5.1 -> 5.2] Extending final classes is not allowed

### ISSUE THREAD

**Issue by mkilmanas** [auth0/symfony#175]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

```
PHP Fatal error:  Class Auth0\Symfony\Models\Stateless\User cannot extend final class Auth0\Symfony\Models\User in /xyz/vendor/auth0/symfony/src/Models/Stateless/User.php on line 9
```

Same issue for `Auth0\Symfony\Models\Stateful\User;` too

### Reproduction

Call `Auth0\Symfony\Security\UserProvider::loadUserByIdentifier('...jwt token...');`

### jwt-auth-bundle version

5.2.0

### Symfony version

6.4

### PHP version

8.2

**Comment by evansims** [comment]
Fixed, thanks!
