### ISSUE TITLE
[5.2] type/visibility mismatches for `User::$roleAuthenticatedUsing`

### ISSUE THREAD

**Issue by mkilmanas** [auth0/symfony#176]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There are multiple issues regarding the type and visibility of the `Auth0\Symfony\Models\User::$roleAuthenticatedUsing`

1. It appears to be intended purely for overriding classes, but declared as `private` -> should be `protected`
2. The extending classes (stateless and stateful User) both: 
    a. override with their own `protected` property
    b. override with a different data type (`array` vs `string`)
    c. do not declare any type on the overridden property at all
3. There is a 'warning: Array to string conversion in /xyz/vendor/auth0/symfony/src/Models/User.php line 152` when using the base `User` class directly, because it declares default value as `[]`, then adds it to array which generally consists of strings, and then `array_unique` is called, which has to convert this `[]` to string in order to compare it to other string elements in the array.

### Reproduction

Call `Auth0\Symfony\Models\User::getRoles()`

### jwt-auth-bundle version

5.2.0

### Symfony version

6.4

### PHP version

8.2

**Comment by evansims** [comment]
Fixed, thanks
