### ISSUE TITLE
Feature Request: Support for Symfony 7.0

### ISSUE THREAD

**Issue by evansims** [auth0/symfony#182]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/symfony#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/symfony/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, our library doesn't have support for Symfony 7.0. Our team's bandwidth is a bit tight at the moment, and I can't offer an ETA of when we'll be able to get around to this, but this is on our radar. Apologies for the delay.

### Describe the ideal solution

If someone out there is willing to put the work in and create a pull request adding this support, it would be most welcome. Keep in mind:

- Ideally, we'd like to maintain 6.4 LTS compatibility alongside adding 7.0 support, if possible. Understandably, that may not be possible.
- All existing tests must pass. (Use `composer test` to run them locally.)

We'd very much like to expand the code coverage of our PEST suite on this package, which has fallen behind the 100% coverage of our PHP and Laravel SDKs. If anyone is willing to assist on that as well we'd appreciate the help.

**Comment by mkilmanas** [comment]
What's the status of this?
Any plans?
Any particular known issues?
Anything contributors could help with?

Looking forward to this as this is blocking us from upgrading to Symfony7

**Comment by evansims** [comment]
Hi @mkilmanas, as mentioned we don't presently have bandwidth to tackle this and can't offer an ETA, but PRs are welcome.

**Comment by gusdeboer** [comment]
Any news on this?

**Comment by abunch** [comment]
@evansims and the PR @mkilmanas submitted for this one too?

**Comment by evansims** [comment]
Experimental, community-contributed support has shipped as part of [5.3.0](https://github.com/auth0/symfony/releases/tag/5.3.0); thanks for your work on this, as well as your other contributions, @mkilmanas. Much appreciated!

If anyone out there can give us a thorough review of our 7.0 support with their apps, and report back with any issues, it'd be much appreciated!
